### ISSUE TITLE
Npaw: Follow up on tvos bug where "+" becomes " "

### ISSUE THREAD

**Issue by andreasgangso** [bcc-code/bcc-media-tvos#12]
Communication is happening via email.
See #13

**Comment by andreasgangso** [comment]
I sent a follow up email now

**Comment by andreasgangso** [comment]
To test:
- Release new version
- Wait a couple of days and see if correct data arrives all the way to bigquery (metabase)

**Comment by mulundapm** [comment]
Release is blocked by tax form but by looking into the npaw qa tool, the user ids from tvos currently contains +
