### ISSUE TITLE
Unable to swipe back to navigation bar on tvos

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-tvos#18]
Its on current prod 4.2.21 and beta 4.2.32 on tvos

Repro:
1. Open bccm app on tvos
2. Swipe down to the 3 slider
3. swipe up to first slider

https://github.com/user-attachments/assets/23f8897f-820c-49ec-a747-17607ec45bff

**Comment by sifferhans** [comment]
https://github.com/bcc-code/bcc-media-tvos/pull/21
