### ISSUE TITLE
Complete tvOS MVP

### ISSUE THREAD

**Issue by fredrikvedvik** [bcc-code/bcc-media-tvos#2]
These are the features missing in tvOS to call it a ready MVP.

- [x] NPAW
- [x] Rudderstack
- [x] Continue watching/progress tracking (?)

**Comment by mulundapm** [comment]
Is npaw available now? That I can see stats from tvOS there?

**Comment by fredrikvedvik** [comment]
> Is npaw available now? That I can see stats from tvOS there?

Yes, in the dev account.

**Comment by mulundapm** [comment]
Events
- [x] Screen/Page View
- [x] Section click (section_clicked)
- [x] Search (search_performed)
- [x] Search Result click (searchresult_clicked)
- [x] Open (application_opened)
https://github.com/bcc-code/bcc-media-adr/blob/master/02-analytics/technical.md
