### ISSUE TITLE
tvOS review

### ISSUE THREAD

**Issue by mulundapm** [bcc-code/bcc-media-tvos#3]
~~- [x] 1. Navigation bar be visible when user scroll to the top of pages~~
- [x] 2. Progress bar on continue watching
- [x] 3. Live in top feature banner
- [x] 4. White boarder for highlights items (FFFFFF 80% 4px outside)
- [x] 5. About page
- [x] 6. More spacing in episode list below player
- [x] 7. Padding should not vary between featured items. (Should also have a bit more on the bottom).
- [ ] 8. Clicking items sometimes doesn't do anything except cause the item to get stuck with a white border until you click something else (only seen on the category pages).
- [x] 9. More padding between sections (see screenshots)
- [ ] 10. App left to home screen / crashed the first time I clicked "back" on the remote from a subpage.
- [x] 11. "Timetable is in your local time" should not show if there's no items.
- [x] 12. Live thumbnail should be scaled down instead of cropped.
- [x] 13. Padding on text on feature banner should align
- [x] 14. Grid view for episode search results
- [x] 15. Clicking back from episode page, should land on the item that was previously selected
- [x] 16. Remove navigation bar on sub pages
- [x] 17. Add app version on the bottom of setting page
- [x] 18. Full screen login page
- [x] 19. When login is clicked, open directly the login page

[About page.pdf](https://github.com/bcc-code/bcc-media-tvos/files/11485516/About.page.pdf)

**Screenshots**
7., 11. and 12. about featured and tv-guide:
<img src="https://user-images.githubusercontent.com/727125/239533183-c6385c24-4a26-47b0-adae-821ecdb1972a.jpg" data-canonical-src="https://user-images.githubusercontent.com/727125/239533183-c6385c24-4a26-47b0-adae-821ecdb1972a.jpg" width="350"  />

9. padding between sections
<img src="https://user-images.githubusercontent.com/727125/239533903-3ec97a2e-1901-4b98-aa5c-02f893e72add.jpg" data-canonical-src="https://user-images.githubusercontent.com/727125/239533903-3ec97a2e-1901-4b98-aa5c-02f893e72add.jpg" width="350"  />
<img src="https://user-images.githubusercontent.com/727125/239533855-c7177c86-5890-44e9-92a2-67ff260e3a94.jpg" data-canonical-src="https://user-images.githubusercontent.com/727125/239533855-c7177c86-5890-44e9-92a2-67ff260e3a94.jpg" width="350"  />

13. Padding on text for feature banner

![Image](https://github.com/bcc-code/bcc-media-tvos/assets/88234679/244dd163-b0bd-4c5c-b29e-679b63c04e34)

**Comment by andreasgangso** [comment]
@fredrikved updated with 7.-12.

**Comment by mulundapm** [comment]
After 15-17 are fixed, could put app in review but dont release yet. So that its available for open beta testing
